/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recordings */
        get: operations["list_recordings_api_recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recording Detail */
        get: operations["recording_detail_api_recordings__recording_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItem */
        ActionItem: {
            /** Assignee */
            assignee?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Task */
            task: string;
        };
        /** ApiErrorBody */
        ApiErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorBody"];
        };
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Content Sha256 */
            content_sha256: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Relative Path */
            relative_path: string;
            /** Revision */
            revision: number;
            /** Schema Version */
            schema_version: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobResponse */
        JobResponse: {
            /** Attempts */
            attempts: number;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: string;
            /** Input Revision */
            input_revision: number;
            /** Kind */
            kind: string;
            /** Settings Fingerprint */
            settings_fingerprint: string;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
        };
        /** MeetingSummary */
        MeetingSummary: {
            /** Action Items */
            action_items: components["schemas"]["ActionItem"][];
            /** Decisions */
            decisions: string[];
            /** Discussion */
            discussion: string[];
            /** Open Questions */
            open_questions: string[];
            /** Purpose */
            purpose: string;
        };
        /** RecordingDetailResponse */
        RecordingDetailResponse: {
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactResponse"][];
            /** Jobs */
            jobs: components["schemas"]["JobResponse"][];
            recording: components["schemas"]["RecordingItem"];
            /** Segments */
            segments: components["schemas"]["SegmentResponse"][];
            summary: components["schemas"]["MeetingSummary"] | null;
        };
        /** RecordingItem */
        RecordingItem: {
            /** Category */
            category: string | null;
            /** Category Confidence */
            category_confidence: number | null;
            /** Category Reason */
            category_reason: string | null;
            /** Created At */
            created_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Id */
            id: string;
            /** Needs Speaker Review */
            needs_speaker_review: boolean;
            /** Original Name */
            original_name: string;
            /** Revision */
            revision: number;
            status: components["schemas"]["RecordingStatus"];
            /** Updated At */
            updated_at: string;
        };
        /** RecordingListResponse */
        RecordingListResponse: {
            /** Items */
            items: components["schemas"]["RecordingItem"][];
            /**
             * Page Size
             * @default 50
             */
            page_size: number;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /**
         * RecordingStatus
         * @enum {string}
         */
        RecordingStatus: "DISCOVERED" | "TRANSCRIBING" | "SPEAKER_REVIEW" | "CLASSIFYING" | "READY_FOR_SUMMARY" | "SUMMARIZING" | "COMPLETED" | "FAILED";
        /** SegmentResponse */
        SegmentResponse: {
            /**
             * Assignment Status
             * @enum {string}
             */
            assignment_status: "assigned" | "overlap" | "unassigned";
            /** End Ms */
            end_ms: number;
            /** Id */
            id: string;
            /** Local Speaker Id */
            local_speaker_id: string | null;
            /** Overlapping Speaker Ids */
            overlapping_speaker_ids: string[];
            /** Person Id */
            person_id: string | null;
            /** Revision */
            revision: number;
            /** Speaker Name */
            speaker_name: string | null;
            /** Start Ms */
            start_ms: number;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_recordings_api_recordings_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RecordingStatus"] | null;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recording_detail_api_recordings__recording_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
