/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/media/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Media */
        get: operations["get_media_api_media__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Persons */
        get: operations["list_persons_api_persons_get"];
        put?: never;
        /** Create Person */
        post: operations["create_person_api_persons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Person */
        patch: operations["update_person_api_persons__person_id__patch"];
        trace?: never;
    };
    "/api/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recordings */
        get: operations["list_recordings_api_recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recording Detail */
        get: operations["recording_detail_api_recordings__recording_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/speakers/{local_speaker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign Recording Speaker */
        put: operations["assign_recording_speaker_api_recordings__recording_id__speakers__local_speaker_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/speakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign Segments */
        patch: operations["assign_segments_api_segments_speakers_patch"];
        trace?: never;
    };
    "/api/segments/{segment_id}/speaker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign Segment */
        patch: operations["assign_segment_api_segments__segment_id__speaker_patch"];
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItem */
        ActionItem: {
            /** Assignee */
            assignee?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Task */
            task: string;
        };
        /** ApiErrorBody */
        ApiErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorBody"];
        };
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Content Sha256 */
            content_sha256: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Revision */
            revision: number;
            /** Schema Version */
            schema_version: number;
        };
        /** BatchSpeakerAssignmentRequest */
        BatchSpeakerAssignmentRequest: {
            /** Expected Revision */
            expected_revision: number;
            /** Person Id */
            person_id: string | null;
            /** Recording Id */
            recording_id: string;
            /** Segment Ids */
            segment_ids: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobResponse */
        JobResponse: {
            /** Attempts */
            attempts: number;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: string;
            /** Input Revision */
            input_revision: number;
            /** Kind */
            kind: string;
            /** Settings Fingerprint */
            settings_fingerprint: string;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
        };
        /** MeetingSummary */
        MeetingSummary: {
            /** Action Items */
            action_items: components["schemas"]["ActionItem"][];
            /** Decisions */
            decisions: string[];
            /** Discussion */
            discussion: string[];
            /** Open Questions */
            open_questions: string[];
            /** Purpose */
            purpose: string;
        };
        /** PersonCreateRequest */
        PersonCreateRequest: {
            /** Display Name */
            display_name: string;
        };
        /** PersonListResponse */
        PersonListResponse: {
            /** Items */
            items: components["schemas"]["PersonResponse"][];
            /** Total */
            total: number;
        };
        /** PersonResponse */
        PersonResponse: {
            /** Created At */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /** Revision */
            revision: number;
            /** Updated At */
            updated_at: string;
        };
        /** PersonUpdateRequest */
        PersonUpdateRequest: {
            /** Display Name */
            display_name: string;
            /** Expected Revision */
            expected_revision: number;
        };
        /** RecordingDetailResponse */
        RecordingDetailResponse: {
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactResponse"][];
            /** Jobs */
            jobs: components["schemas"]["JobResponse"][];
            recording: components["schemas"]["RecordingItem"];
            /** Segments */
            segments: components["schemas"]["SegmentResponse"][];
            summary: components["schemas"]["MeetingSummary"] | null;
        };
        /** RecordingItem */
        RecordingItem: {
            /** Category */
            category: string | null;
            /** Category Confidence */
            category_confidence: number | null;
            /** Category Reason */
            category_reason: string | null;
            /** Created At */
            created_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Id */
            id: string;
            /** Needs Speaker Review */
            needs_speaker_review: boolean;
            /** Original Name */
            original_name: string;
            /** Revision */
            revision: number;
            status: components["schemas"]["RecordingStatus"];
            /** Updated At */
            updated_at: string;
        };
        /** RecordingListResponse */
        RecordingListResponse: {
            /** Items */
            items: components["schemas"]["RecordingItem"][];
            /**
             * Page Size
             * @default 50
             */
            page_size: number;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /**
         * RecordingStatus
         * @enum {string}
         */
        RecordingStatus: "DISCOVERED" | "TRANSCRIBING" | "SPEAKER_REVIEW" | "CLASSIFYING" | "READY_FOR_SUMMARY" | "SUMMARIZING" | "COMPLETED" | "FAILED";
        /** SegmentResponse */
        SegmentResponse: {
            /**
             * Assignment Status
             * @enum {string}
             */
            assignment_status: "assigned" | "overlap" | "unassigned";
            /** End Ms */
            end_ms: number;
            /** Id */
            id: string;
            /** Local Speaker Id */
            local_speaker_id: string | null;
            /** Overlapping Speaker Ids */
            overlapping_speaker_ids: string[];
            /** Person Id */
            person_id: string | null;
            /** Revision */
            revision: number;
            /** Speaker Name */
            speaker_name: string | null;
            /** Speaker Score */
            speaker_score: number | null;
            /**
             * Speaker Source
             * @enum {string}
             */
            speaker_source: "manual" | "auto" | "unresolved";
            /** Start Ms */
            start_ms: number;
            /** Text */
            text: string;
        };
        /** SpeakerAssignmentRequest */
        SpeakerAssignmentRequest: {
            /** Expected Revision */
            expected_revision: number;
            /** Person Id */
            person_id: string | null;
        };
        /** SpeakerAssignmentResponse */
        SpeakerAssignmentResponse: {
            /** Person Id */
            person_id: string | null;
            /** Recording Id */
            recording_id: string;
            /** Recording Revision */
            recording_revision: number;
            /** Speaker Name */
            speaker_name: string | null;
            /** Updated Segment Count */
            updated_segment_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_media_api_media__artifact_id__get: {
        parameters: {
            query?: never;
            header?: {
                Range?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Requested Range Not Satisfiable */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_persons_api_persons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonListResponse"];
                };
            };
        };
    };
    create_person_api_persons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    update_person_api_persons__person_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recordings_api_recordings_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RecordingStatus"] | null;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recording_detail_api_recordings__recording_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_recording_speaker_api_recordings__recording_id__speakers__local_speaker_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
                local_speaker_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerAssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerAssignmentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    assign_segments_api_segments_speakers_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchSpeakerAssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerAssignmentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    assign_segment_api_segments__segment_id__speaker_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerAssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerAssignmentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
