/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/media/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Media */
        get: operations["get_media_api_media__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Persons */
        get: operations["list_persons_api_persons_get"];
        put?: never;
        /** Create Person */
        post: operations["create_person_api_persons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Person */
        patch: operations["update_person_api_persons__person_id__patch"];
        trace?: never;
    };
    "/api/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recordings */
        get: operations["list_recordings_api_recordings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recording Detail */
        get: operations["recording_detail_api_recordings__recording_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Category */
        patch: operations["update_category_api_recordings__recording_id__category_patch"];
        trace?: never;
    };
    "/api/recordings/{recording_id}/retranscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Retranscription */
        post: operations["create_retranscription_api_recordings__recording_id__retranscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/retranscriptions/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Retranscription */
        get: operations["latest_retranscription_api_recordings__recording_id__retranscriptions_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/speakers/{local_speaker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Assign Recording Speaker */
        put: operations["assign_recording_speaker_api_recordings__recording_id__speakers__local_speaker_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Summary */
        post: operations["request_summary_api_recordings__recording_id__summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/segments/speakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign Segments */
        patch: operations["assign_segments_api_segments_speakers_patch"];
        trace?: never;
    };
    "/api/segments/{segment_id}/speaker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign Segment */
        patch: operations["assign_segment_api_segments__segment_id__speaker_patch"];
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItem */
        ActionItem: {
            /** Assignee */
            assignee?: string | null;
            /** Due Date */
            due_date?: string | null;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Task */
            task: string;
        };
        /** AffectedRecordingResponse */
        AffectedRecordingResponse: {
            /** Recording Id */
            recording_id: string;
            /** Recording Revision */
            recording_revision: number;
            render_job: components["schemas"]["RenderJobResponse"];
        };
        /** ApiErrorBody */
        ApiErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            error: components["schemas"]["ApiErrorBody"];
        };
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Content Sha256 */
            content_sha256: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Revision */
            revision: number;
            /** Schema Version */
            schema_version: number;
        };
        /** BatchSpeakerAssignmentRequest */
        BatchSpeakerAssignmentRequest: {
            /** Expected Revision */
            expected_revision: number;
            /** Person Id */
            person_id: string | null;
            /** Recording Id */
            recording_id: string;
            /** Segment Ids */
            segment_ids: string[];
        };
        /** CategoryRenderJobResponse */
        CategoryRenderJobResponse: {
            /** Id */
            id: string;
            /** Input Revision */
            input_revision: number;
            /**
             * Kind
             * @default render
             * @constant
             */
            kind: "render";
            /**
             * Status
             * @default queued
             * @constant
             */
            status: "queued";
        };
        /** CategoryUpdateRequest */
        CategoryUpdateRequest: {
            /** Category */
            category: string;
            /** Expected Revision */
            expected_revision: number;
        };
        /** CategoryUpdateResponse */
        CategoryUpdateResponse: {
            /** Category */
            category: string;
            /**
             * Category Source
             * @default manual
             * @constant
             */
            category_source: "manual";
            /** Recording Id */
            recording_id: string;
            render_job: components["schemas"]["CategoryRenderJobResponse"];
            /** Revision */
            revision: number;
        };
        /** DailyConversationSummary */
        DailyConversationSummary: {
            /** Agreements */
            agreements: components["schemas"]["SummaryFact"][];
            /** Main Topics */
            main_topics: components["schemas"]["SummaryFact"][];
            /** Reminders */
            reminders: components["schemas"]["SummaryFact"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "daily_conversation";
        };
        /** Evidence */
        Evidence: {
            /** End Ms */
            end_ms: number;
            /** Quote */
            quote?: string | null;
            /**
             * Segment Id
             * Format: uuid
             */
            segment_id: string;
            /** Start Ms */
            start_ms: number;
        };
        /** GameListSummary */
        GameListSummary: {
            /** Follow Ups */
            follow_ups: components["schemas"]["SummaryFact"][];
            /** Games */
            games: components["schemas"]["SummaryFact"][];
            /** Preferences */
            preferences: components["schemas"]["SummaryFact"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "game_list";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobResponse */
        JobResponse: {
            /** Attempts */
            attempts: number;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Id */
            id: string;
            /** Input Revision */
            input_revision: number;
            /** Kind */
            kind: string;
            /** Settings Fingerprint */
            settings_fingerprint: string;
            /** Status */
            status: string;
            /** Updated At */
            updated_at: string;
        };
        /** LectureSummary */
        LectureSummary: {
            /** Concepts */
            concepts: components["schemas"]["SummaryFact"][];
            /** Core Topics */
            core_topics: components["schemas"]["SummaryFact"][];
            /** Examples */
            examples: components["schemas"]["SummaryFact"][];
            /** Review Items */
            review_items: components["schemas"]["SummaryFact"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "lecture";
        };
        /** MeetingSummary */
        MeetingSummary: {
            /** Action Items */
            action_items: components["schemas"]["ActionItem"][];
            /** Decisions */
            decisions: components["schemas"]["SummaryFact"][];
            /** Discussion */
            discussion: components["schemas"]["SummaryFact"][];
            /** Open Questions */
            open_questions: components["schemas"]["SummaryFact"][];
            purpose: components["schemas"]["SummaryFact"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "meeting";
        };
        /** OtherSummary */
        OtherSummary: {
            /** Follow Ups */
            follow_ups: components["schemas"]["SummaryFact"][];
            /** Key Facts */
            key_facts: components["schemas"]["SummaryFact"][];
            key_summary: components["schemas"]["SummaryFact"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "other";
        };
        /** PersonCreateRequest */
        PersonCreateRequest: {
            /** Display Name */
            display_name: string;
        };
        /** PersonListResponse */
        PersonListResponse: {
            /** Items */
            items: components["schemas"]["PersonResponse"][];
            /** Total */
            total: number;
        };
        /** PersonResponse */
        PersonResponse: {
            /** Created At */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /** Revision */
            revision: number;
            /** Updated At */
            updated_at: string;
        };
        /** PersonUpdateRequest */
        PersonUpdateRequest: {
            /** Display Name */
            display_name: string;
            /** Expected Revision */
            expected_revision: number;
        };
        /** PersonUpdateResponse */
        PersonUpdateResponse: {
            /** Affected Recordings */
            affected_recordings: components["schemas"]["AffectedRecordingResponse"][];
            /** Created At */
            created_at: string;
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            /** Revision */
            revision: number;
            /** Updated At */
            updated_at: string;
        };
        /** RecordingDetailResponse */
        RecordingDetailResponse: {
            /** Allowed Categories */
            allowed_categories: string[];
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactResponse"][];
            /** Jobs */
            jobs: components["schemas"]["JobResponse"][];
            recording: components["schemas"]["RecordingItem"];
            /** Segments */
            segments: components["schemas"]["SegmentResponse"][];
            /** Speakers */
            speakers: components["schemas"]["RecordingSpeakerResponse"][];
            /** Summary */
            summary: (components["schemas"]["LectureSummary"] | components["schemas"]["MeetingSummary"] | components["schemas"]["DailyConversationSummary"] | components["schemas"]["GameListSummary"] | components["schemas"]["OtherSummary"]) | null;
        };
        /** RecordingItem */
        RecordingItem: {
            /** Automatic Category */
            automatic_category: string | null;
            /** Category */
            category: string | null;
            /** Category Confidence */
            category_confidence: number | null;
            /** Category Reason */
            category_reason: string | null;
            /** Category Source */
            category_source: ("auto" | "manual") | null;
            /** Created At */
            created_at: string;
            /** Duration Ms */
            duration_ms: number;
            /** Id */
            id: string;
            /** Needs Speaker Review */
            needs_speaker_review: boolean;
            /** Original Name */
            original_name: string;
            /** Revision */
            revision: number;
            status: components["schemas"]["RecordingStatus"];
            /** Updated At */
            updated_at: string;
        };
        /** RecordingListResponse */
        RecordingListResponse: {
            /** Items */
            items: components["schemas"]["RecordingItem"][];
            /**
             * Page Size
             * @default 50
             */
            page_size: number;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /** RecordingSpeakerResponse */
        RecordingSpeakerResponse: {
            /** Clip Error Code */
            clip_error_code: string | null;
            /**
             * Clip Status
             * @enum {string}
             */
            clip_status: "pending" | "ready" | "insufficient" | "failed";
            /** Duration Ms */
            duration_ms: number;
            /** Local Speaker Id */
            local_speaker_id: string;
            match?: components["schemas"]["SpeakerMatchResponse"] | null;
            /** Person Id */
            person_id: string | null;
            /** Representative Clip Artifact Id */
            representative_clip_artifact_id: string | null;
            /** Representative Clip End Ms */
            representative_clip_end_ms: number | null;
            /** Representative Clip Start Ms */
            representative_clip_start_ms: number | null;
            /** Segment Count */
            segment_count: number;
            /** Speaker Name */
            speaker_name: string | null;
            /** Speaker Score */
            speaker_score: number | null;
            /**
             * Speaker Source
             * @enum {string}
             */
            speaker_source: "manual" | "auto" | "unresolved";
        };
        /**
         * RecordingStatus
         * @enum {string}
         */
        RecordingStatus: "DISCOVERED" | "TRANSCRIBING" | "SPEAKER_REVIEW" | "CLASSIFYING" | "READY_FOR_SUMMARY" | "SUMMARIZING" | "COMPLETED" | "FAILED";
        /** RenderJobResponse */
        RenderJobResponse: {
            /** Id */
            id: string;
            /** Input Revision */
            input_revision: number;
            /**
             * Kind
             * @default render
             */
            kind: string;
            /**
             * Status
             * @default queued
             */
            status: string;
        };
        /** RetranscriptionCreateRequest */
        RetranscriptionCreateRequest: {
            /**
             * Confirm Impact
             * @constant
             */
            confirm_impact: true;
            /** Content Description */
            content_description?: string | null;
            /** Expected Revision */
            expected_revision: number;
            /**
             * Language
             * @default auto
             * @enum {string}
             */
            language: "auto" | "ko" | "en" | "ja";
            /** Terms */
            terms?: string[];
        };
        /** RetranscriptionCreateResponse */
        RetranscriptionCreateResponse: {
            /** Base Revision */
            base_revision: number;
            /** Hint Applied */
            hint_applied: boolean;
            job: components["schemas"]["RetranscriptionJobResponse"];
            /** Language */
            language: string;
            /** Recording Id */
            recording_id: string;
            /** Request Id */
            request_id: string;
            /** Target Revision */
            target_revision: number;
            /** Warning */
            warning: string;
        };
        /** RetranscriptionJobResponse */
        RetranscriptionJobResponse: {
            /** Id */
            id: string;
            /** Input Revision */
            input_revision: number;
            /**
             * Kind
             * @default transcribe
             */
            kind: string;
            /** Status */
            status: string;
        };
        /** RetranscriptionLatestResponse */
        RetranscriptionLatestResponse: {
            /** Base Revision */
            base_revision: number;
            /** Created At */
            created_at: string;
            /** Error Code */
            error_code: string | null;
            /** Hint Applied */
            hint_applied: boolean;
            /** History Available */
            history_available: boolean;
            /** History Location */
            history_location: string | null;
            /** New Language */
            new_language: string | null;
            /** New Segment Count */
            new_segment_count: number | null;
            /** Previous Language */
            previous_language: string | null;
            /** Previous Segment Count */
            previous_segment_count: number;
            /** Recording Id */
            recording_id: string;
            /** Request Id */
            request_id: string;
            /** Requested Language */
            requested_language: string;
            /** Status */
            status: string;
            /** Target Revision */
            target_revision: number;
            /** Unresolved Speaker Count */
            unresolved_speaker_count: number | null;
            /** Updated At */
            updated_at: string;
        };
        /** SegmentResponse */
        SegmentResponse: {
            /**
             * Assignment Status
             * @enum {string}
             */
            assignment_status: "assigned" | "overlap" | "unassigned";
            /** End Ms */
            end_ms: number;
            /** Id */
            id: string;
            /** Local Speaker Id */
            local_speaker_id: string | null;
            /** Overlapping Speaker Ids */
            overlapping_speaker_ids: string[];
            /** Person Id */
            person_id: string | null;
            /** Revision */
            revision: number;
            /** Speaker Name */
            speaker_name: string | null;
            /** Speaker Score */
            speaker_score: number | null;
            /**
             * Speaker Source
             * @enum {string}
             */
            speaker_source: "manual" | "auto" | "unresolved";
            /** Start Ms */
            start_ms: number;
            /** Text */
            text: string;
        };
        /** SpeakerAssignmentRequest */
        SpeakerAssignmentRequest: {
            /** Expected Revision */
            expected_revision: number;
            /** Person Id */
            person_id: string | null;
        };
        /** SpeakerAssignmentResponse */
        SpeakerAssignmentResponse: {
            /** Person Id */
            person_id: string | null;
            /** Recording Id */
            recording_id: string;
            /** Recording Revision */
            recording_revision: number;
            render_job: components["schemas"]["RenderJobResponse"];
            /** Speaker Name */
            speaker_name: string | null;
            /** Updated Segment Count */
            updated_segment_count: number;
        };
        /** SpeakerMatchCandidateResponse */
        SpeakerMatchCandidateResponse: {
            /** Display Name */
            display_name: string;
            /** Person Id */
            person_id: string;
            /** Rank */
            rank: number;
            /** Rejected */
            rejected: boolean;
            /** Score */
            score: number;
        };
        /** SpeakerMatchResponse */
        SpeakerMatchResponse: {
            /** Best Score */
            best_score: number;
            /** Candidates */
            candidates: components["schemas"]["SpeakerMatchCandidateResponse"][];
            /**
             * Decision
             * @enum {string}
             */
            decision: "insufficient_clips" | "no_profiles" | "insufficient_profiles" | "auto_disabled" | "below_threshold" | "insufficient_margin" | "duplicate_person" | "rejected_candidate" | "auto_matched";
            /** Input Revision */
            input_revision: number;
            /** Margin */
            margin: number;
            /** Second Best Score */
            second_best_score: number;
        };
        /** SummaryFact */
        SummaryFact: {
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /** Text */
            text: string;
        };
        /** SummaryRequest */
        SummaryRequest: {
            /** Expected Revision */
            expected_revision: number;
        };
        /** SummaryRequestResponse */
        SummaryRequestResponse: {
            /** Created */
            created: boolean;
            /** Job Id */
            job_id: string;
            /**
             * Job Status
             * @enum {string}
             */
            job_status: "queued" | "running" | "succeeded";
            /** Recording Id */
            recording_id: string;
            /** Revision */
            revision: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_media_api_media__artifact_id__get: {
        parameters: {
            query?: never;
            header?: {
                Range?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Requested Range Not Satisfiable */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_persons_api_persons_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonListResponse"];
                };
            };
        };
    };
    create_person_api_persons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    update_person_api_persons__person_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonUpdateResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recordings_api_recordings_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RecordingStatus"] | null;
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recording_detail_api_recordings__recording_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_recordings__recording_id__category_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryUpdateResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    create_retranscription_api_recordings__recording_id__retranscriptions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetranscriptionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetranscriptionCreateResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_retranscription_api_recordings__recording_id__retranscriptions_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetranscriptionLatestResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_recording_speaker_api_recordings__recording_id__speakers__local_speaker_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
                local_speaker_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerAssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerAssignmentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    request_summary_api_recordings__recording_id__summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SummaryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryRequestResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    assign_segments_api_segments_speakers_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchSpeakerAssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerAssignmentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    assign_segment_api_segments__segment_id__speaker_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerAssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerAssignmentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
